### PR TITLE
Fix start_with method call

### PR DESCRIPTION
**Pull request by JaredMiller**
start_with rather than starts_with

### CODE REVIEW

**Comment by kmcphillips** [comment]
Thanks. I'm going to release `1.2.1` today so it will be included in that.

**Comment by kmcphillips** [comment]
Introduced in 53c0e4d9ed2abc6fffc5bbe6d13189a1b928dc62 cc @trishume

**Comment by kmcphillips** [comment]
So this is an `ActiveSupport` alias:
https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/activesupport/lib/active_support/core_ext/string/starts_ends_with.rb#L2

Was this a bug for you? We have `ActiveSupport` as an explicit dependency.

**Comment by JaredMiller** [comment]
@kmcphillips Yes, I was getting no method errors last night after upgrading from a very old version of active_shipping

It was failing on a very simple test file

    require 'json'
    require 'active_shipping'
    require 'yaml'
    include ActiveShipping
    
    loginConfig = YAML::load(File.open('<config file>'))
    usps_api = USPS.new(:login => loginConfig['usps']['login_name'])
    response = usps_api.find_tracking_info('9574211132094339557534')

**Comment by kmcphillips** [comment]
Oh this is very interesting.

So we depend on active support but we don't actually require it anywhere. Since you're working outside of a `Gemfile` in the above example it's not being loaded automatically.

We'll change it so that we explicitly `require "active_support"`. @trishume has offered to PR that.

**Comment by trishume** [comment]
https://github.com/Shopify/active_shipping/blob/master/lib/active_shipping.rb#L24 :neutral_face:

Now I'm even more confused. I have no idea why you were getting those errors.

**Comment by trishume** [comment]
Ok at least I can reproduce it locally. Still no idea why this is happening though.

**Comment by wvanbergen** [comment]
`require 'active_support'` doesn't actually load much. If you want to load all of AS, do `require 'active_support/all'`

**Comment by wvanbergen** [comment]
If you include ActiveShipping in a Rails app, you won't likely run into this because Rails will load the necessary part of ActiveSupport.

**Comment by trishume** [comment]
Thanks @wvanbergen that explains a lot. Now I know why it didn't also crash from the calls to `try`. I implemented this fix in #274.

**Pull request merged**
