### PR TITLE
Swap incorrect height and width defaults for UPS labels

### PR DESCRIPTION
**Pull request by wassimk**
In #326 it was noted the labels are coming in sideways possibly because the height and width are swapped. I tested it and they come through sideways no matter what. But, this corrects that typo regardless.

### CODE REVIEW

**Comment by kmcphillips** [comment]
Can you get the tests passing please? Then I will merge.

**Comment by kmcphillips** [comment]
Bump. If you want this released in the next version.

**Comment by wassimk** [comment]
I did more testing and I believe the height and width are indeed swapped in the UPS API. I reverted my changes and documented the code more. I'm still doing testing though. I'm going to request a 4 x 8 label and see that it returns what's expected.

I think the current failed test for delivery estimate is because UPS doesn't deliver on New Years Day.

**Comment by kmcphillips** [comment]
I'm going to close this out. If you get test covering it and some supporting documentation for this change, feel free to re-open.

**Pull request closed without merging**
