### PR TITLE
UPS SurePost API requires OZS for packages < 1lb

### PR DESCRIPTION
**Pull request by epixhints**

### CODE REVIEW

**Comment by epixhints** [comment]
SurePost is contractual, so it will always fail if it's not set up w/ UPS. Any suggestions on removing the remote test vs. suppressing it?

**Comment by wvanbergen** [comment]
My preferred solution to this is to create a separate set of credentials, and a separate remote test class. The remote tests will be skipped if no credentials are provided. We have a similar setup for different Canada Post accounts.

**Comment by epixhints** [comment]
@wvanbergen cool idea. done.

**Comment by epixhints** [comment]
@wvanbergen friendly ping.

**Comment by wvanbergen** [comment]
Changes look OK to me, but I don't have time to look into this deeper any time soon. Maybe @trishume can look at this?

**Comment by trishume** [comment]
Looks good, thanks! :+1: 

CI failure is unrelated to this PR.

I'll ship a new version of active_shipping with this change sometime soon.

**Comment by trishume** [comment]
This was released in v1.4.3, thanks for contributing!

**Comment by epixhints** [comment]
Thanks!

**Pull request merged**
