### PR TITLE
Refactored setters on rate estimate

### PR DESCRIPTION
**Pull request by MalazAlamir**
Small refactor on `rate_estimate` that moves the private method to a protected visibility and creates a setter for `delivery_range`.

cc/ @jonathankwok @cyprusad

### CODE REVIEW

**Comment by jonathankwok** [comment]
LGTM. CC: @RichardBlair @kmcphillips

**Comment by kmcphillips** [comment]
This changes the visibility of `date_for` too.

**Comment by kmcphillips** [comment]
Is the setter going to be used elsewhere? Otherwise it should probably stay in the initializer. It breaks the existing pattern of making all the properties immutable.

**Comment by RichardBlair** [comment]
@kmcphillips We had a discussion in a Shopify repo.

Essentially there are cases where you may want to initialize a `RateEstimate` and then fill in more details later. If you want to do this, you currently would need to write a setter, and copy the logic from the initializer in your setter. By moving this to a protected setter we encapsulate the logic, and allow subclasses of `RateEstimate` access those setters, and potentially expose them publicly when needed.

@MalazAlamir :shipit:

**Comment by RichardBlair** [comment]
Actually, Malaz, can you create setters for all the attributes that are set to fill out the interface?

**Comment by MalazAlamir** [comment]
@RichardBlair yep, will do. I'll create setters for the attributes that go through some sort of logic in `initialize`

**Comment by MalazAlamir** [comment]
reping @jonathankwok @cyprusad after new changes

**Comment by jonathankwok** [comment]
Nice, I like the reworked interface. :shipit:

**Comment by cyprusad** [comment]
:ship:

**Pull request merged**
