### PR TITLE
UPS needs shipment Description for cross-border

### PR DESCRIPTION
**Pull request by jamesroscoe**
UPS requires shipment description in order to deliver a product from Canada to the US (and probably any time customs clearance is required). Pass as {description: "description"} in the options hash to Ups#create_shipment.

### CODE REVIEW

**Comment by wvanbergen** [comment]
Can this be rebased on the latest master? We rewrote the UPS carrier using Nokogiri.

**Comment by jamesroscoe** [comment]
I guess I'll have to. I've been making other changes for adding a paperless Commercial Invoice. That will probably need to get redone as well.

**Comment by eboswort** [comment]
@jamesroscoe Hey!
I just saw this PR, and I wish I'd seen it a month ago cause I actually created a PR, #237 that overlaps with this a ton since I'm also shipping across borders. That one got merged, but yours has a lot of prettiness that mine did not. However you should have a look at mine because it adds a lot of the same structure and does so using Nokogiri.

I'd love to help you get this PR merged into master. I feel like we could get a lot more people contributing to active_shipping's UPS code if we could just flesh it out a bit more.

Although I'm thinking maybe it'd be easier to break this up into smaller PR's since it covers so much.
Are you down with the plan of splitting it up? 

I could help. For instance I was just about to create a PR doing basically exactly what you did in your last two commits related to delivery_confirmation. I like how you did it so I could cherry pick those commits for you and rebase and create a new PR. You'd still be the author on the commits. I'm assuming you'd be cool with that?

**Comment by jamesroscoe** [comment]
Hi Eli,

I've got no problem with you doing that. I was going to redo it for Nokogiri when I got a chance. I have been tempted to go through and make a class that maps the entire UPS XML shipment interface but that's a huge task. It's just that each time my customer asks me to check something I find it's not there (yet) so I keep having to add stuff.

James

**Pull request closed without merging**
