### PR TITLE
Add public remote test creds and fix test

### PR DESCRIPTION
**Pull request by trishume**
Adds back the creds removed in https://github.com/Shopify/active_shipping/pull/284 because I changed the password back to what it was.

Also adds an old Jaded Pixel (former name for Shopify Inc.) login for USPS. Was assured by USPS that nothing too bad could happen if it was released publicly.

Also fixes a test that failed only on Fridays :neutral_face:.

@kmcphillips @RichardBlair

### CODE REVIEW

**Comment by jnormore** [comment]
> Also fixes a test that failed only on Fridays

lol

**Comment by wvanbergen** [comment]
This is the best :+1: Thanks for putting all this work on making this project more healthy!

**Comment by RichardBlair** [comment]
:heart:

**Pull request merged**
