### PR TITLE
Ups shipment event code

### PR DESCRIPTION
**Pull request by rsierra**
Parse the type code of each shipment event in tracking response.

### CODE REVIEW

**Comment by eboswort** [comment]
LGTM Guess it's failing on some USPS stuff

**Comment by rsierra** [comment]
Yeah,but I don't really change nothing for USPS, it's just for UPS. I had no problems with the local unit test, but I forgot the remote ones. I will try to take a look :-).

**Comment by eboswort** [comment]
Oh no, I didn't mean to imply you had anything to do with the USPS errors. I feel confident you did not break those.

**Comment by rsierra** [comment]
Ok, thx!

**Comment by trishume** [comment]
This was released in v1.4.3, thanks for contributing!

**Pull request merged**
