### PR TITLE
Parse delivery date for FedEx Ground Home Delivery rate estimates

### PR DESCRIPTION
**Pull request by ajsharma**
Fixes https://github.com/Shopify/active_shipping/issues/278

### CODE REVIEW

**Comment by kmcphillips** [comment]
Could we get some test coverage for this?

**Comment by ajsharma** [comment]
@kmcphillips :+1: working on it now :smile:

**Comment by ajsharma** [comment]
I've added a test for the behavior, hope it's enough :worried:

**Comment by trishume** [comment]
:+1:

Not sure if that XML blob should be included in its entirety though. It's enormous. Might be useful reference but I think some redaction might be in order.

**Comment by kmcphillips** [comment]
:+1: but also agree with possibly trimming the unused part of the XML, if possible.

**Comment by ajsharma** [comment]
:+1: will do :)

**Comment by ajsharma** [comment]
I removed all the shipping options besides the relevant ground shipping one. Is there anything else I should clean up?

**Comment by trishume** [comment]
Looks good, I'll merge this somewhat soonish when I do the next release. Thanks for the contribution!

**Pull request merged**
