### PR TITLE
Add missing UPS service name to code mapping.

### PR DESCRIPTION
**Pull request by gavinballard**

### CODE REVIEW

**Comment by kmcphillips** [comment]
Do you have links to the docs for this? Can you get CI green?

**Comment by gavinballard** [comment]
As far as I know, the UPS developer docs aren't publicly available, so I'm afraid I can't link to what I have. The docs I do have give `14` as the service code for `Next Day Air Early AM` shipments.

The issue I was running into that this fixes is the same as the existing two `DEFAULT_SERVICE_NAME_TO_CODE` lines - the UPS Time in Transit API returns alternate versions of service names (eg `UPS 2nd Day Air` instead of `UPS Second Day Air` or `UPS Next Day Air Early` instead of `UPS Next Day Air Early A.M.`). This trips up the service code mapper [here](https://github.com/Shopify/active_shipping/blob/438c954c7bd8827073ddccc3203d3e90431dea6a/lib/active_shipping/carriers/ups.rb#L841).

As to the failing tests - I'm happy to look into it if you can give me guidance, but considering how minor the changes in this PR are, I think there may be some underlying issues with the tests.

**Comment by kmcphillips** [comment]
@gavinballard I got `Shopify/active_shipping` `master` green again. Can you pull down the changes and get your build passing? Ping me once it's green and I'll merge.

**Comment by gavinballard** [comment]
Ping @kmcphillips! :)

**Comment by kmcphillips** [comment]
Released in 1.6.2

**Pull request merged**
